# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('assigned_user_id', models.IntegerField()),
                ('created_user_id', models.IntegerField()),
                ('created_date_time', models.DateTimeField()),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('ticket_attachment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_file_name', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=50)),
                ('created_user_id', models.IntegerField()),
                ('created_date_time', models.DateTimeField()),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('ticket_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticket_text', models.TextField()),
                ('created_user_id', models.IntegerField()),
                ('created_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('priority_id', models.IntegerField(primary_key=True, serialize=False)),
                ('priority_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TicketStatus'),
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TicketDetail'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TicketPriority'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TicketStatus'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TicketType'),
        ),
    ]
