# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='priority_id',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='ticketattachment',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='ticketattachment',
            old_name='ticket_detail_id',
            new_name='ticket_detail',
        ),
        migrations.RenameField(
            model_name='ticketdetail',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='ticketdetail',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
