# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_ticket_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='ticket_detail',
        ),
        migrations.RemoveField(
            model_name='ticketdetail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticketdetail',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketAttachment',
        ),
        migrations.DeleteModel(
            name='TicketDetail',
        ),
    ]
