# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20161202_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
