# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20161205_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 6, 9, 27, 9, 394866)),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 6, 9, 27, 9, 395574)),
        ),
    ]
