# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20161206_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 6, 11, 21, 53, 318673)),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 6, 11, 21, 53, 319951)),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 6, 11, 21, 53, 319428)),
        ),
    ]
