# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20161216_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 5, 7, 32, 4498)),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='reset_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 5, 7, 32, 2864)),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 5, 7, 32, 4049)),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 5, 7, 32, 3537)),
        ),
    ]
