# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 07:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20161216_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpassword',
            name='created_user_id',
        ),
        migrations.AddField(
            model_name='resetpassword',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 7, 52, 48, 47384)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 7, 52, 48, 45670)),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 7, 52, 48, 46924)),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 7, 52, 48, 46407)),
        ),
    ]
