# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20161216_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 7, 16, 48, 377897)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 7, 16, 48, 376193)),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 7, 16, 48, 377428)),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 7, 16, 48, 376902)),
        ),
    ]
