# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 06:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20170112_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 12, 11, 51, 25, 712879)),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 12, 11, 51, 25, 712304)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 12, 11, 51, 25, 710628)),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 12, 11, 51, 25, 711837)),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 12, 11, 51, 25, 711311)),
        ),
    ]
